---
title: "Webapp: application.properties renamed and completed."
type: change
description: |
  * application.properties is now renamed axelor-config.properties.
  * See [AOP documentation](https://docs.axelor.com/adk/latest/migrations/migration-6.0.html#configurations-naming) for parameter changes related to AOP.
  * aos.api.enable is renamed to utils.api.enable and is now true by default.
  * aos.apps.install-apps is renamed studio.apps.install
  * axelor.report.use.embedded.engine is renamed reports.aos.use-embedded-engine
  * axelor.report.engine is renamed reports.aos.external-engine
  * axelor.report.resource.path is renamed reports.aos.resource-path
